# Generated by Django 6.0.4 on 2026-06-05 12:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('slug', models.SlugField(blank=True, max_length=120, unique=True)),
                ('icon', models.CharField(choices=[('wrench', 'Llave'), ('bolt', 'Tornillo'), ('broom', 'Escoba'), ('brush', 'Brocha'), ('hammer', 'Martillo'), ('leaf', 'Hoja'), ('truck', 'Camión'), ('snow', 'Nieve'), ('key', 'Llave (cerrajería)'), ('chip', 'Chip'), ('scissors', 'Tijeras'), ('book', 'Libro')], default='wrench', max_length=20)),
                ('hero', models.CharField(blank=True, help_text='URL o ruta de la imagen de encabezado de la categoría.', max_length=500)),
                ('description', models.TextField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
                ('order', models.PositiveIntegerField(default=0, help_text='Orden de aparición.')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Categoría',
                'verbose_name_plural': 'Categorías',
                'db_table': 'categories',
                'ordering': ['order', 'name'],
                'indexes': [models.Index(fields=['is_active'], name='categories_is_acti_aae090_idx'), models.Index(fields=['slug'], name='categories_slug_b4303a_idx')],
            },
        ),
    ]
