# Generated by Django 6.0.4 on 2026-06-05 12:45

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0002_professionalprofile_gallery_and_more'),
        ('categories', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_number', models.CharField(editable=False, max_length=20, unique=True)),
                ('service_title', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('scheduled_for', models.DateTimeField(blank=True, null=True)),
                ('location', models.CharField(blank=True, max_length=255)),
                ('agreed_price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('status', models.CharField(choices=[('scheduled', 'Agendada'), ('completed', 'Completada'), ('cancelled', 'Cancelada'), ('no_show', 'No asistió')], default='scheduled', max_length=20)),
                ('source', models.CharField(choices=[('chat', 'Agendada en chat'), ('direct', 'Contacto directo')], default='chat', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='orders', to='categories.category')),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='orders_as_client', to=settings.AUTH_USER_MODEL)),
                ('professional', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='orders', to='accounts.professionalprofile')),
            ],
            options={
                'db_table': 'orders',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['order_number'], name='orders_order_n_1336be_idx'), models.Index(fields=['status'], name='orders_status_762191_idx')],
            },
        ),
    ]
