# Generated by Django 6.0.4 on 2026-06-05 12:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='professionalprofile',
            name='gallery',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='professionalprofile',
            name='handle',
            field=models.CharField(blank=True, help_text='Alias público: "@marcos.rivera".', max_length=80),
        ),
        migrations.AddField(
            model_name='professionalprofile',
            name='headline',
            field=models.CharField(blank=True, help_text='Título corto: "Plomero certificado · 12 años".', max_length=200),
        ),
        migrations.AddField(
            model_name='professionalprofile',
            name='is_top_pro',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='professionalprofile',
            name='location',
            field=models.CharField(blank=True, help_text='Ciudad / zona: "Madrid, Centro".', max_length=200),
        ),
        migrations.AddField(
            model_name='professionalprofile',
            name='price_from',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Precio por hora "desde".', max_digits=8, null=True),
        ),
        migrations.AddField(
            model_name='professionalprofile',
            name='response_time_min',
            field=models.PositiveIntegerField(blank=True, help_text='Tiempo medio de respuesta en minutos.', null=True),
        ),
        migrations.AddField(
            model_name='professionalprofile',
            name='schedule',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='professionalprofile',
            name='skills',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='professionalprofile',
            name='years_experience',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
